config/routes.rb
Rails.application.routes.draw do
  resources :ticketprice_collections
  resources :showroom_collections
  resources :ticketprices
  resources :showpieces
  resources :collections
  resources :showrooms

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :showpieces
  has_many :showroom_collections
  has_many :ticketprice_collections
  
  validates :name, presence: true, uniqueness: {scope: [:start_date, 
:end_date]}
  validates :start_date, presence: true
  validates :end_date, presence: true
  
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name, :start_date, :end_date, :description)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.haml
= form_for @collection do |f|
  - if @collection.errors.any?
    #error_explanation
      %h2= "#{pluralize(@collection.errors.count, "error")} prohibited this collection from being saved:"
      %ul
        - @collection.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :start_date
    = f.date_select :start_date
  .field
    = f.label :end_date
    = f.date_select :end_date
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/collections/edit.html.haml
%h1 Editing collection

= render 'form'

= link_to 'Show', @collection
\|
= link_to 'Back', collections_path

app/views/collections/index.html.haml
%h1 Listing collections

%table
  %thead
    %tr
      %th Name
      %th Start date
      %th End date
      %th Description
      %th
      %th
      %th

  %tbody
    - @collections.each do |collection|
      %tr
        %td= collection.name
        %td= collection.start_date
        %td= collection.end_date
        %td= collection.description
        %td= link_to 'Show', collection
        %td= link_to 'Edit', edit_collection_path(collection)
        %td= link_to 'Destroy', collection, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Collection', new_collection_path

app/views/collections/new.html.haml
%h1 New collection

= render 'form'

= link_to 'Back', collections_path

app/views/collections/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @collection.name
%p
  %b Start date:
  = @collection.start_date
%p
  %b End date:
  = @collection.end_date
%p
  %b Description:
  = @collection.description

= link_to 'Edit', edit_collection_path(@collection)
\|
= link_to 'Back', collections_path