config/routes.rb
Rails.application.routes.draw do
  resources :ticketprice_collections
  resources :showroom_collections
  resources :ticketprices
  resources :showpieces
  resources :collections
  resources :showrooms

end

app/models/showroom_collection.rb
class ShowroomCollection < ActiveRecord::Base
  belongs_to :showroom
  belongs_to :collection

  validates :showroom_id, presence: true, uniqueness: {scope: 
:collection_id}
  validates :collection_id, presence: true
end

app/controllers/showroom_collections_controller.rb
class ShowroomCollectionsController < ApplicationController
  before_action :set_showroom_collection, only: [:show, :edit, :update, :destroy]

  # GET /showroom_collections
  # GET /showroom_collections.json
  def index
    @showroom_collections = ShowroomCollection.all
  end

  # GET /showroom_collections/1
  # GET /showroom_collections/1.json
  def show
  end

  # GET /showroom_collections/new
  def new
    @showroom_collection = ShowroomCollection.new
  end

  # GET /showroom_collections/1/edit
  def edit
  end

  # POST /showroom_collections
  # POST /showroom_collections.json
  def create
    @showroom_collection = ShowroomCollection.new(showroom_collection_params)

    respond_to do |format|
      if @showroom_collection.save
        format.html { redirect_to @showroom_collection, notice: 'Showroom collection was successfully created.' }
        format.json { render :show, status: :created, location: @showroom_collection }
      else
        format.html { render :new }
        format.json { render json: @showroom_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /showroom_collections/1
  # PATCH/PUT /showroom_collections/1.json
  def update
    respond_to do |format|
      if @showroom_collection.update(showroom_collection_params)
        format.html { redirect_to @showroom_collection, notice: 'Showroom collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @showroom_collection }
      else
        format.html { render :edit }
        format.json { render json: @showroom_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /showroom_collections/1
  # DELETE /showroom_collections/1.json
  def destroy
    @showroom_collection.destroy
    respond_to do |format|
      format.html { redirect_to showroom_collections_url, notice: 'Showroom collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_showroom_collection
      @showroom_collection = ShowroomCollection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def showroom_collection_params
      params.require(:showroom_collection).permit(:showroom_id_id, :collection_id_id)
    end
end

app/helpers/showroom_collections_helper.rb
module ShowroomCollectionsHelper
end

app/views/showroom_collections/_form.html.haml
= form_for @showroom_collection do |f|
  - if @showroom_collection.errors.any?
    #error_explanation
      %h2= "#{pluralize(@showroom_collection.errors.count, "error")} prohibited this showroom_collection from being saved:"
      %ul
        - @showroom_collection.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :showroom_id
    = f.text_field :showroom_id
  .field
    = f.label :collection_id
    = f.text_field :collection_id
  .actions
    = f.submit 'Save'

app/views/showroom_collections/edit.html.haml
%h1 Editing showroom_collection

= render 'form'

= link_to 'Show', @showroom_collection
\|
= link_to 'Back', showroom_collections_path

app/views/showroom_collections/index.html.haml
%h1 Listing showroom_collections

%table
  %thead
    %tr
      %th Showroom
      %th Collection
      %th
      %th
      %th

  %tbody
    - @showroom_collections.each do |showroom_collection|
      %tr
        %td= showroom_collection.showroom_id
        %td= showroom_collection.collection_id
        %td= link_to 'Show', showroom_collection
        %td= link_to 'Edit', edit_showroom_collection_path(showroom_collection)
        %td= link_to 'Destroy', showroom_collection, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Showroom collection', new_showroom_collection_path

app/views/showroom_collections/new.html.haml
%h1 New showroom_collection

= render 'form'

= link_to 'Back', showroom_collections_path

app/views/showroom_collections/show.html.haml
%p#notice= notice

%p
  %b Showroom:
  = @showroom_collection.showroom_id
%p
  %b Collection:
  = @showroom_collection.collection_id

= link_to 'Edit', edit_showroom_collection_path(@showroom_collection)
\|
= link_to 'Back', showroom_collections_path