config/routes.rb
Rails.application.routes.draw do
  resources :ticketprice_collections
  resources :showroom_collections
  resources :ticketprices
  resources :showpieces
  resources :collections
  resources :showrooms

end

app/models/showroom.rb
class Showroom < ActiveRecord::Base
  has_many :showroom_collections

  validates :name, presence: true, uniqueness: true

end

app/controllers/showrooms_controller.rb
class ShowroomsController < ApplicationController
  before_action :set_showroom, only: [:show, :edit, :update, :destroy]

  # GET /showrooms
  # GET /showrooms.json
  def index
    @showrooms = Showroom.all
  end

  # GET /showrooms/1
  # GET /showrooms/1.json
  def show
  end

  # GET /showrooms/new
  def new
    @showroom = Showroom.new
  end

  # GET /showrooms/1/edit
  def edit
  end

  # POST /showrooms
  # POST /showrooms.json
  def create
    @showroom = Showroom.new(showroom_params)

    respond_to do |format|
      if @showroom.save
        format.html { redirect_to @showroom, notice: 'Showroom was successfully created.' }
        format.json { render :show, status: :created, location: @showroom }
      else
        format.html { render :new }
        format.json { render json: @showroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /showrooms/1
  # PATCH/PUT /showrooms/1.json
  def update
    respond_to do |format|
      if @showroom.update(showroom_params)
        format.html { redirect_to @showroom, notice: 'Showroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @showroom }
      else
        format.html { render :edit }
        format.json { render json: @showroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /showrooms/1
  # DELETE /showrooms/1.json
  def destroy
    @showroom.destroy
    respond_to do |format|
      format.html { redirect_to showrooms_url, notice: 'Showroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_showroom
      @showroom = Showroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def showroom_params
      params.require(:showroom).permit(:name)
    end
end

app/helpers/showrooms_helper.rb
module ShowroomsHelper
end

app/views/showrooms/_form.html.haml
= form_for @showroom do |f|
  - if @showroom.errors.any?
    #error_explanation
      %h2= "#{pluralize(@showroom.errors.count, "error")} prohibited this showroom from being saved:"
      %ul
        - @showroom.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/showrooms/edit.html.haml
%h1 Editing showroom

= render 'form'

= link_to 'Show', @showroom
\|
= link_to 'Back', showrooms_path

app/views/showrooms/index.html.haml
%h1 Listing showrooms

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @showrooms.each do |showroom|
      %tr
        %td= showroom.name
        %td= link_to 'Show', showroom
        %td= link_to 'Edit', edit_showroom_path(showroom)
        %td= link_to 'Destroy', showroom, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Showroom', new_showroom_path

app/views/showrooms/new.html.haml
%h1 New showroom

= render 'form'

= link_to 'Back', showrooms_path

app/views/showrooms/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @showroom.name

= link_to 'Edit', edit_showroom_path(@showroom)
\|
= link_to 'Back', showrooms_path