config/routes.rb
Rails.application.routes.draw do
  resources :ticketprice_collections
  resources :showroom_collections
  resources :ticketprices
  resources :showpieces
  resources :collections
  resources :showrooms

end

app/models/ticketprice.rb
class Ticketprice < ActiveRecord::Base
  has_many :ticketprice_collections

  
  VISITOR_TYPES = {0=>"взрослый", 1=>"детский", 2=>"иностранный 
гражданин", 3=>"студент", 4=>"инвалид" }

  validates :price, numericality: {greater_than: 0}
  validates :visitor_type, presence: true, inclusion: {in: 
VISITOR_TYPES.keys}


end

app/controllers/ticketprices_controller.rb
class TicketpricesController < ApplicationController
  before_action :set_ticketprice, only: [:show, :edit, :update, :destroy]

  # GET /ticketprices
  # GET /ticketprices.json
  def index
    @ticketprices = Ticketprice.all
  end

  # GET /ticketprices/1
  # GET /ticketprices/1.json
  def show
  end

  # GET /ticketprices/new
  def new
    @ticketprice = Ticketprice.new
  end

  # GET /ticketprices/1/edit
  def edit
  end

  # POST /ticketprices
  # POST /ticketprices.json
  def create
    @ticketprice = Ticketprice.new(ticketprice_params)

    respond_to do |format|
      if @ticketprice.save
        format.html { redirect_to @ticketprice, notice: 'Ticketprice was successfully created.' }
        format.json { render :show, status: :created, location: @ticketprice }
      else
        format.html { render :new }
        format.json { render json: @ticketprice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticketprices/1
  # PATCH/PUT /ticketprices/1.json
  def update
    respond_to do |format|
      if @ticketprice.update(ticketprice_params)
        format.html { redirect_to @ticketprice, notice: 'Ticketprice was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticketprice }
      else
        format.html { render :edit }
        format.json { render json: @ticketprice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticketprices/1
  # DELETE /ticketprices/1.json
  def destroy
    @ticketprice.destroy
    respond_to do |format|
      format.html { redirect_to ticketprices_url, notice: 'Ticketprice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticketprice
      @ticketprice = Ticketprice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticketprice_params
      params.require(:ticketprice).permit(:visitor_type, :price)
    end
end

app/helpers/ticketprices_helper.rb
module TicketpricesHelper
end

app/views/ticketprices/_form.html.haml
= form_for @ticketprice do |f|
  - if @ticketprice.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ticketprice.errors.count, "error")} prohibited this ticketprice from being saved:"
      %ul
        - @ticketprice.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :visitor_type
    = f.number_field :visitor_type
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = f.submit 'Save'

app/views/ticketprices/edit.html.haml
%h1 Editing ticketprice

= render 'form'

= link_to 'Show', @ticketprice
\|
= link_to 'Back', ticketprices_path

app/views/ticketprices/index.html.haml
%h1 Listing ticketprices

%table
  %thead
    %tr
      %th Visitor type
      %th Price
      %th
      %th
      %th

  %tbody
    - @ticketprices.each do |ticketprice|
      %tr
        %td= ticketprice.visitor_type
        %td= ticketprice.price
        %td= link_to 'Show', ticketprice
        %td= link_to 'Edit', edit_ticketprice_path(ticketprice)
        %td= link_to 'Destroy', ticketprice, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Ticketprice', new_ticketprice_path

app/views/ticketprices/new.html.haml
%h1 New ticketprice

= render 'form'

= link_to 'Back', ticketprices_path

app/views/ticketprices/show.html.haml
%p#notice= notice

%p
  %b Visitor type:
  = @ticketprice.visitor_type
%p
  %b Price:
  = @ticketprice.price

= link_to 'Edit', edit_ticketprice_path(@ticketprice)
\|
= link_to 'Back', ticketprices_path